In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',]

In [ ]:
voc_size = 10000

In [ ]:
onehot_repr = [one_hot(words, voc_size) for words in sent]
print(onehot_repr)

[[5421, 8540, 3115, 5591], [5421, 8540, 3115, 3044], [5421, 6003, 3115, 8041], [6437, 8300, 2897, 3708, 6624], [6437, 8300, 2897, 3708, 7494], [7327, 5421, 5392, 3115, 1130], [2807, 7162, 5920, 3708]]


In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [ ]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5421 8540 3115 5591]
 [   0    0    0    0 5421 8540 3115 3044]
 [   0    0    0    0 5421 6003 3115 8041]
 [   0    0    0 6437 8300 2897 3708 6624]
 [   0    0    0 6437 8300 2897 3708 7494]
 [   0    0    0 7327 5421 5392 3115 1130]
 [   0    0    0    0 2807 7162 5920 3708]]


In [ ]:
#feature space - mapping each word into a space of 10 elements
#columnar matrix of 10 elements
dim = 10

In [ ]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
embedded_docs[0]
# not necessary

array([   0,    0,    0,    0, 5421, 8540, 3115, 5591], dtype=int32)

In [ ]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 125ms/step
[[ 0.04946407 -0.04268306  0.02910674  0.04699628  0.00133646  0.0149386
  -0.00736661 -0.0210826   0.02268911  0.0351599 ]
 [ 0.04946407 -0.04268306  0.02910674  0.04699628  0.00133646  0.0149386
  -0.00736661 -0.0210826   0.02268911  0.0351599 ]
 [ 0.04946407 -0.04268306  0.02910674  0.04699628  0.00133646  0.0149386
  -0.00736661 -0.0210826   0.02268911  0.0351599 ]
 [ 0.04946407 -0.04268306  0.02910674  0.04699628  0.00133646  0.0149386
  -0.00736661 -0.0210826   0.02268911  0.0351599 ]
 [ 0.0058931   0.04675246  0.01061523  0.03153317  0.02670446 -0.04652261
   0.02134318 -0.00601411  0.00489441  0.03836348]
 [-0.04924807 -0.0234826  -0.01443421 -0.04612707 -0.00266696  0.00273166
   0.03889084 -0.0324076   0.00251088 -0.04369063]
 [-0.04802718  0.02802472  0.03116265  0.02140305  0.03150118  0.03919813
  -0.031461    0.01763913 -0.00249947 -0.00754063]
 [-0.02327094 -0.04233306 -0.03149148 -0.0060912  -0.01522334  0.04629717
  

In [ ]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 23ms/step
[[[ 4.94640730e-02 -4.26830649e-02  2.91067399e-02  4.69962843e-02
    1.33645535e-03  1.49385966e-02 -7.36660883e-03 -2.10826043e-02
    2.26891078e-02  3.51598971e-02]
  [ 4.94640730e-02 -4.26830649e-02  2.91067399e-02  4.69962843e-02
    1.33645535e-03  1.49385966e-02 -7.36660883e-03 -2.10826043e-02
    2.26891078e-02  3.51598971e-02]
  [ 4.94640730e-02 -4.26830649e-02  2.91067399e-02  4.69962843e-02
    1.33645535e-03  1.49385966e-02 -7.36660883e-03 -2.10826043e-02
    2.26891078e-02  3.51598971e-02]
  [ 4.94640730e-02 -4.26830649e-02  2.91067399e-02  4.69962843e-02
    1.33645535e-03  1.49385966e-02 -7.36660883e-03 -2.10826043e-02
    2.26891078e-02  3.51598971e-02]
  [ 5.89310005e-03  4.67524566e-02  1.06152296e-02  3.15331705e-02
    2.67044567e-02 -4.65226062e-02  2.13431828e-02 -6.01410866e-03
    4.89441305e-03  3.83634828e-02]
  [-4.92480658e-02 -2.34825965e-02 -1.44342072e-02 -4.61270697e-02
   -2.66696140e-03  2.73165852e